name: Build and Release PaperDreams

on:
  push:
    tags:
      - 'v*'   # Trigger only when pushing a version tag like v1.0.0
  workflow_dispatch:  # Allow manual runs

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pygame

      - name: Build executable with PyInstaller
        run: |
          python - <<'EOF'
          import os
          import PyInstaller.__main__

          sep = os.pathsep
          PyInstaller.__main__.run([
              "--onefile",
              "--name", "PaperDreams",
              f"--add-data=PaperDreams/graphics{sep}graphics",
              f"--add-data=PaperDreams/music{sep}music",
              "PaperDreams/extra2.py"
          ])
          EOF

      - name: Archive build
        run: |
          mkdir dist_upload
          cd dist
          zip -r ../dist_upload/PaperDreams-${{ matrix.os }}.zip .
        shell: bash

      - name: Upload build as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PaperDreams-${{ matrix.os }}
          path: dist_upload/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release_files

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release_files/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
